server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  h2:
   console:
     enabled: true
     path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  application:
    name: votesApp
  jpa:
   database: H2
   show-sql: true
   hibernate:
    ddl-auto: update  
  
  

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true